# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dean Magee
tagline:          'Stats, Machine Learning and Web Development'
description:      'A collection of my work'
url:              http://dean12.github.io
baseurl:          /

author:
  name:           'Dean Magee'
  url:            au.linkedin.com/in/deanmagee1

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dean12
